version: '3.7'

services:
  opendeck:
    container_name: opendeck
    image: ghcr.io/shanteacontrols/opendeck
    volumes:
      - $PWD:/home/ubuntu/OpenDeck
    working_dir: /home/ubuntu/OpenDeck
    command: tail -f /dev/null