version: '3.7'

services:
  opendeck:
    container_name: opendeck
    hostname: opendeck
    image: ghcr.io/shanteacontrols/opendeck
    volumes:
      - $PWD:/home/ubuntu/workspace/OpenDeck
      - $HOME/.ssh:/home/ubuntu/.ssh
      - /dev:/dev
    working_dir: /home/ubuntu/workspace/OpenDeck
    command: tail -f /dev/null
    privileged: true