version: '3.7'

services:
  opendeck:
    container_name: opendeck
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - $PWD:/home/ubuntu/workspace/OpenDeck
      - $HOME/.ssh:/home/ubuntu/.ssh
      - /dev:/dev
    hostname: localhost
    working_dir: /home/ubuntu/workspace/OpenDeck
    command: tail -f /dev/null
    privileged: true