---
  flash:
    app-start-page: 0
  fuses:
    unlock: 0xFF
    lock: 0xEF
    ext: 0xFC
    high: 0xD0
    low: 0xFF
  adc:
    prescaler: 128
    samples: 1
  uart:
    buffers:
      tx: 128
      rx: 128
  i2c:
    buffers:
      tx: 64
      rx: 64