---
  flash:
    boot-start-page: 0
    app-start-page: 5
    app-boot-jump-offset: 4
    emueeprom:
      factory-page:
        page: 2
      page1:
        page: 3
      page2:
        page: 4
  adc:
    prescaler: 4
    samples: 16
  usb:
    endpoints:
      midi:
        in: 0x81
        out: 0x02
        size:
          in-out: 32
          control: 64
      midi-cdc-dual:
        cdc-in: 0x81
        cdc-out: 0x01
        cdc-notification: 0x83
        midi-in: 0x82
        midi-out: 0x02
        size:
          midi-in-out: 32
          cdc-in-out: 32
          cdc-notification: 8
          control: 64
    buffers:
      midi:
        tx: 4096
        rx: 4096
      cdc:
        tx: 2048
        rx: 2048
  include-dirs:
    - "src/board/src/common/communication/usb/tinyusb"
  uart:
    buffers:
      tx: 128
      rx: 128
  i2c:
    buffers:
      tx: 64
      rx: 64
