---
  flash:
    boot-start-page: 0
    app-start-page: 2
    app-boot-jump-offset: 4
    emueeprom:
      factory-page:
        page: 6
      page1:
        page: 7
      page2:
        page: 8
  adc:
    prescaler: 8
    samples: 16
  usb:
    endpoints:
      size:
        control: 64
        midi-in-out: 32
        cdc-in-out: 32
        cdc-notification: 8
      midi:
        in: 0x81
        out: 0x02
      midi-cdc-dual:
        cdc-in: 0x81
        cdc-out: 0x01
        cdc-notification: 0x83
        midi-in: 0x82
        midi-out: 0x02
    buffers:
      midi:
        tx: 4096
        rx: 4096
      cdc:
        tx: 2048
        rx: 2048
  include-dirs:
    - "src/board/src/common/communication/usb/tinyusb"
  uart:
    buffers:
      tx: 128
      rx: 128
  i2c:
    buffers:
      tx: 64
      rx: 64
