---
  mcu: "atmega2560"
  extClockMhz: 16
  usb: false
  uart:
    usbLink:
      channel: 0
      type: "device"
    dinMIDI:
      channel: 1
  i2c:
    display:
      channel: 0
  buttons:
    type: "native"
    pins:
    -
      port: "B"
      index: 1
    -
      port: "B"
      index: 3
    -
      port: "L"
      index: 1
    -
      port: "L"
      index: 3
    -
      port: "L"
      index: 5
    -
      port: "L"
      index: 7
    -
      port: "G"
      index: 1
    -
      port: "D"
      index: 7
    -
      port: "C"
      index: 1
    -
      port: "C"
      index: 3
    -
      port: "C"
      index: 5
    -
      port: "C"
      index: 7
    -
      port: "A"
      index: 6
    -
      port: "A"
      index: 4
    -
      port: "A"
      index: 2
    -
      port: "A"
      index: 0
    -
      port: "B"
      index: 0
    -
      port: "B"
      index: 2
    -
      port: "L"
      index: 0
    -
      port: "L"
      index: 2
    -
      port: "L"
      index: 4
    -
      port: "L"
      index: 6
    -
      port: "G"
      index: 0
    -
      port: "G"
      index: 2
    -
      port: "C"
      index: 0
    -
      port: "C"
      index: 2
    -
      port: "C"
      index: 4
    -
      port: "C"
      index: 6
    -
      port: "A"
      index: 7
    -
      port: "A"
      index: 5
    -
      port: "A"
      index: 3
    -
      port: "A"
      index: 1
  analog:
    type: "native"
    inputVoltage: "5.0"
    pins:
    -
      port: "F"
      index: 0
    -
      port: "F"
      index: 1
    -
      port: "F"
      index: 2
    -
      port: "F"
      index: 3
    -
      port: "F"
      index: 4
    -
      port: "F"
      index: 5
    -
      port: "F"
      index: 6
    -
      port: "F"
      index: 7
    -
      port: "K"
      index: 0
    -
      port: "K"
      index: 1
    -
      port: "K"
      index: 2
    -
      port: "K"
      index: 3
    -
      port: "K"
      index: 4
    -
      port: "K"
      index: 5
    -
      port: "K"
      index: 6
    -
      port: "K"
      index: 7
  leds:
    external:
      type: "native"
      pins:
      -
        port: "J"
        index: 0
      -
        port: "J"
        index: 1
      -
        port: "E"
        index: 4
      -
        port: "E"
        index: 5
      -
        port: "G"
        index: 5
      -
        port: "E"
        index: 3
      -
        port: "H"
        index: 3
      -
        port: "H"
        index: 4
      -
        port: "H"
        index: 5
      -
        port: "H"
        index: 6
      -
        port: "B"
        index: 4
      -
        port: "B"
        index: 5
      -
        port: "B"
        index: 6
      -
        port: "B"
        index: 7
  test: true