---
  mcu: "atmega16u2"
  extClockMhz: 16
  targetNameOverride: "mega2560"
  usb: true
  uart:
    usbLink:
      channel: 0
      type: "host"
  leds:
    internal:
      invert: true
      pins:
        usb:
          rx:
            port: "D"
            index: 4
          tx:
            port: "D"
            index: 5
        uart:
          rx:
            port: "D"
            index: 4
          tx:
            port: "D"
            index: 5