---
  mcu: "atmega2560"
  extClockMhz: 16
  usb: false
  uart:
    usbLink:
      channel: 0
      type: "device"
    dinMIDI:
      channel: 1
  i2c:
    display:
      channel: 0
  buttons:
    type: "native"
    pins:
    -
      port: "B"
      index: 1
    -
      port: "B"
      index: 3
    -
      port: "L"
      index: 1
    -
      port: "L"
      index: 3
    -
      port: "L"
      index: 5
    -
      port: "L"
      index: 7
    -
      port: "G"
      index: 1
    -
      port: "D"
      index: 7
    -
      port: "C"
      index: 1
    -
      port: "C"
      index: 3
    -
      port: "C"
      index: 5
    -
      port: "C"
      index: 7
    -
      port: "A"
      index: 6
    -
      port: "A"
      index: 4
    -
      port: "A"
      index: 2
    -
      port: "A"
      index: 0
    -
      port: "B"
      index: 0
    -
      port: "B"
      index: 2
    -
      port: "L"
      index: 0
    -
      port: "L"
      index: 2
    -
      port: "L"
      index: 4
    -
      port: "L"
      index: 6
    -
      port: "G"
      index: 0
    -
      port: "G"
      index: 2
    -
      port: "C"
      index: 0
    -
      port: "C"
      index: 2
    -
      port: "C"
      index: 4
    -
      port: "C"
      index: 6
    -
      port: "A"
      index: 7
    -
      port: "A"
      index: 5
    -
      port: "A"
      index: 3
    -
      port: "A"
      index: 1
  analog:
    type: "4067"
    inputVoltage: "5.0"
    multiplexers: 3
    pins:
      s0:
        port: "E"
        index: 4
      s1:
        port: "G"
        index: 5
      s2:
        port: "H"
        index: 3
      s3:
        port: "H"
        index: 4
      z0:
        port: "F"
        index: 0
      z1:
        port: "F"
        index: 1
      z2:
        port: "F"
        index: 2
  leds:
    external:
      type: "native"
      pins:
      -
        port: "H"
        index: 0
      -
        port: "H"
        index: 1
      -
        port: "J"
        index: 0
      -
        port: "J"
        index: 1
      -
        port: "E"
        index: 5
      -
        port: "E"
        index: 3
      -
        port: "H"
        index: 6
      -
        port: "B"
        index: 7
  unused-io:
  -
    port: "H"
    index: 5
    mode: "out-low"
  -
    port: "B"
    index: 4
    mode: "out-low"
  -
    port: "B"
    index: 5
    mode: "out-low"
  -
    port: "B"
    index: 6
    mode: "out-low"