name: CI

on: [push]

jobs:
  build_and_test_ubuntu:
    name: Build/Test [Ubuntu]
    runs-on: ubuntu-20.04
    container:
      image: paradajz168/opendeck-dev:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - name: Pull the repository and submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build targets
        run: |
          export MAKEFLAGS=-j$(nproc)
          git fetch --tags
          cd src/
          ../scripts/build_targets.sh
      - name: Test targets
        run: |
          export MAKEFLAGS=-j$(nproc)
          cd tests/
          ../scripts/build_targets.sh
          make exec
  format:
    name: Code formatting
    runs-on: ubuntu-20.04
    container:
      image: paradajz168/opendeck-dev:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Source formatting
        run: |
          cd src
          make format CF_FAIL_ON_DIFF=1
      - name: Test formatting
        run: |
          cd tests
          make format CF_FAIL_ON_DIFF=1
  lint:
    name: Code linting
    runs-on: ubuntu-20.04
    container:
      image: paradajz168/opendeck-dev:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Lint
        run: |
          ./scripts/lint.sh