name: CI

on: [push]

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  CCACHE_DIR: /__w/OpenDeck/OpenDeck/ccache

jobs:
  build_and_test_ubuntu:
    name: Build/Test [Ubuntu]
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/shanteacontrols/opendeck:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - name: Pull the repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Restore ccache
        uses: actions/cache/restore@v4
        with:
          path: |
            ccache
          key: ccache-key
      - name: Build and test targets
        run: |
          git fetch --tags
          ./scripts/build_targets.sh --type=build
          ./scripts/build_targets.sh --type=test
      - name: Save ccache
        uses: actions/cache/save@v4
        with:
          path: |
            ccache
          key: ccache-key
  format:
    name: Code formatting
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/shanteacontrols/opendeck:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Check formatting
        run: |
          make format
  lint:
    name: Code linting
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/shanteacontrols/opendeck:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Lint
        run: |
          ./scripts/build_targets.sh --type=lint