name: Docker

on:
  push:
    branches:
      - "*"
    paths:
      - 'west.yml'
      - '.devcontainer/Dockerfile'

jobs:
  update_docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull the repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to docker hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64, linux/arm64
          file: .devcontainer/Dockerfile
          tags: ghcr.io/shanteacontrols/opendeck:latest