name: Deploy

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    name: Attach firmware to release
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/shanteacontrols/opendeck:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - name: Pull the repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        run: |
          git fetch --tags
          ./scripts/build_targets.sh --type=build
          ./scripts/copy_release_binaries.sh --build-dir=build --copy-dir=release
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          hub release edit $(find ./release -type f -printf "-a %p ") -m "" "$tag_name"