name: Deploy

on:
  release:
    types: [created]

jobs:
  build:
    name: Attach firmware to release
    runs-on: ubuntu-22.04
    container:
      image: paradajz168/opendeck-dev:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/OpenDeck/OpenDeck
      - name: Pull the repository and submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        run: |
          git fetch --tags
          cd src/
          export MAKEFLAGS=-j$(nproc)
          ../scripts/build_targets.sh
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          hub release edit $(find ./src/build -type f -path "*merged*" -name "*.sysex" -not -name "*mega16u2*" -printf "-a %p ") -m "" "$tag_name"
          hub release edit $(find ./src/build -type f -path "*merged*" -not -name "*_sysex.bin" -name "*.bin" -printf "-a %p ") -m "" "$tag_name"
          hub release edit $(find ./src/build -type f -path "*merged*" -name "*.hex" -printf "-a %p ") -m "" "$tag_name"
          hub release edit $(find ./src/build -type f -path "*merged*" -name "*.uf2" -printf "-a %p ") -m "" "$tag_name"